[package]
name = "p2p_rust"
version = "0.1.0"
edition = "2024"
default-run = "main"

[dependencies]
tokio = { version = "1", features = ["full"] }
winit = "0.29"
slint = "1.10.0"

[build-dependencies]
slint-build = "1.10.0" 

[[bin]]
name = "main"
path = "src/main.rs"