[package]
name = "p2p_rust"
version = "0.1.0"
edition = "2024"
default-run = "main"

[dependencies]
tokio = { version = "1", features = ["full"] }
slint = "1.10.0"
rfd = "0.15.3"
egui = "0.31.1"
eframe = "0.31.1"

[build-dependencies]
slint-build = "1.10.0" 


[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "test2"
path = "src/test2.rs"